(deftheme mockingbird
  "A little more than minimal: based on eink theme.")

(custom-theme-set-faces
 'mockingbird
 '(cursor ((t (:background "#111111" :foreground "white smoke"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#111111" :weight bold))))
 '(highlight ((t nil)))
 '(region ((t (:background "#eeeee8" :foreground "#111111"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:background "#fffff8" :foreground "#111111"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "dark green"))))
 '(font-lock-comment-face ((t (:foreground "dark green"))))
 '(font-lock-constant-face ((t (:foreground "#111111"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#111111" :weight semi-bold))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-function-name-face ((t (:weight bold))))
 '(font-lock-keyword-face ((t (:foreground "medium blue"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#111111"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(button ((t (:foreground "#111111" :underline t))))
 '(custom-variable-tag ((t (:foreground "#111111" :weight bold))))
 '(default-italic ((t (:italic t))))
 '(font-latex-bold-face ((t (:foreground "#111111"))))
 '(font-latex-italic-face ((t (:foreground "#111111" :slant italic))))
 '(font-latex-match-reference-keywords ((t (:foreground "#111111"))))
 '(font-latex-match-variable-keywords ((t (:foreground "#111111"))))
 '(font-latex-string-face ((t (:foreground "#a9a9a9"))))
 '(font-lock-reference-face ((t (:foreground "#111111"))))
 '(font-lock-string-face ((t (:foreground "dark red"))))
 '(font-lock-type-face ((t (:foreground "#111111"))))
 '(font-lock-variable-name-face ((t (:foreground "#111111" :underline nil))))
 '(font-lock-warning-face ((t (:foreground "#111111" :weight bold))))
 '(fringe ((t (:background "#fffff8" :foreground "#fffff8"))))
 '(gnus-header-content ((t (:foreground "#111111"))))
 '(gnus-header-from ((t (:foreground "#111111"))))
 '(gnus-header-name ((t (:foreground "#111111"))))
 '(gnus-header-subject ((t (:foreground "#111111"))))
 '(ido-first-match ((t (:foreground "#111111"))))
 '(ido-only-match ((t (:foreground "#111111"))))
 '(ido-subdir ((t (:foreground "#111111"))))
 '(isearch ((t (:background "#eeeee8" :foreground "#111111"))))
 '(link ((t (:foreground "#111111"))))
 '(mode-line ((t (:background "#ddddd8" :foreground "#111111" :height 0.8))))
 '(mode-line-buffer ((t (:foreground "#111111" :weight bold))))
 '(mode-line-inactive ((t (:background "#ddddd8" :foreground "#111111" :height 0.8))))
 '(mode-line-minor-mode ((t (:weight ultra-light))))
 '(modeline ((t (:background "#fffff8" :foreground "#111111" :height 0.8))))
 '(slime-repl-inputed-output-face ((t (:foreground "#111111"))))
 '(whitespace-line ((t (:background "LightCyan" :foreground "#111111"))))
 '(org-agenda-date ((t (:foreground "#111111" :height 1.2))))
 '(org-agenda-date-today ((t (:foreground "#111111" :weight bold :height 1.4))))
 '(org-agenda-date-weekend ((t (:foreground "#111111" :weight normal))))
 '(org-agenda-structure ((t (:foreground "#111111" :weight bold))))
 '(org-block ((t (:foreground "#111111"))))
 '(org-block-begin-line ((t (:foreground "#ddddd8" :height 0.8))))
 '(org-block-end-line ((t (:foreground "#ddddd8" :height 0.8))))
 '(org-verbatim ((t (:foreground "#111111" :weight semi-bold))))
 '(org-date ((t (:foreground "#111111") :underline)))
 '(org-done ((t (:foreground "#ddddd8"))))
 '(org-hide ((t (:foreground "#fffff8"))))
 '(org-level-1 ((t (:foreground "#111111" :weight semi-bold :height 1.3))))
 '(org-level-2 ((t (:foreground "#111111" :weight semi-bold :height 1.1 :overline "#fffff8"))))
 '(org-level-3 ((t (:foreground "#111111" :weight semi-bold :height 1.1 :overline "#fffff8"))))
 '(org-level-4 ((t (:foreground "#111111" :weight semi-bold :height 1.1 :overline "#fffff8"))))
 '(org-level-5 ((t (:foreground "#111111" :weight semi-bold :height 1.1 :overline "#fffff8"))))
 '(org-level-6 ((t (:foreground "#111111" :weight semi-bold :height 1.1 :overline "#fffff8"))))
 '(org-link ((t (:foreground "#111111" :underline t))))
 '(org-quote ((t (:foreground "#111111" :slant italic :inherit org-block))))
 '(org-scheduled ((t (:foreground "#111111"))))
 '(org-sexp-date ((t (:foreground "#111111"))))
 '(org-special-keyword ((t (:foreground "#111111"))))
 '(org-todo ((t (:foreground "#111111"))))
 '(org-verse ((t (:inherit org-block :slant italic))))
 '(org-table ((t (:foreground "#222291"))))
 '(powerline-active1 ((t (:background "grey22" :foreground "#fffff8" :inherit mode-line))))
 '(powerline-active2 ((t (:background "grey40" :foreground "#fffff8" :inherit mode-line))))
 '(magit-header ((t (:weight semi-bold))))
 '(magit-item-mark ((t (:background "#FFF1AA"))))
 '(magit-item-highlight ((t (:weight bold))))
 '(magit-section-heading ((t (:weight semi-bold :height 1.2))))
 '(magit-section-highlight ((t (:weight semi-bold))))
 '(magit-diff-context-highlight ((t (:foreground "#111111"))))
 '(magit-branch-local ((t (:weight bold))))
 '(magit-branch-remote ((t (:weight bold))))
 '(diff-added ((t (:background "#e9ffe9"))))
 '(diff-removed ((t (:background "#ffecec"))))
 '(diff-refine-added ((t (:background "#a4f4a3"))))
 '(diff-refine-removed ((t (:background "#f9cbca"))))
 '(magit-diff-added-highlight ((t (:weight demibold :background "#e9ffe9"))))
 '(magit-diff-added ((t (:background "#e9ffe9"))))
 '(magit-diff-removed-highlight ((t (:weight demibold :background "#ffecec"))))
 '(magit-diff-removed ((t (:background "#ffecec"))))
 '(git-timemachine-minibuffer-author-face ((t (:inherit default))))
 '(git-timemachine-minibuffer-detail-face ((t (:weight bold))))
 '(compilation-error ((t (:inherit error))))
 '(flycheck-error ((t (:inherit error))))
 '(flycheck-warning ((t (:inherit warning))))
 '(dired-directory ((t (:weight bold))))
 '(dired-subtree-depth-1-face ((t (:inherit default))))
 '(dired-subtree-depth-2-face ((t (:inherit default))))
 '(dired-subtree-depth-3-face ((t (:inherit default))))
 '(dired-subtree-depth-4-face ((t (:inherit default))))
 '(helm-source-header ((t (:foreground "#111111" :background "grey90" :weight bold))))
 '(helm-header ((t (:foreground "#111111"))))
 '(helm-selection-line ((t (:inherit region :weight bold))))
 '(helm-selection ((t (:background "#FFF1AA"))))
 '(helm-ff-directory ((t (:foreground "#111111" :weight bold))))
 '(helm-ff-dotted-directory ((t (:foreground "#111111" :weight bold))))
 '(helm-ff-symlink ((t (:foreground "#111111" :slant italic))))
 '(helm-ff-executable ((t (:foreground "#111111"))))
 '(iedit-occurrence ((t (:background "LightGreen" :foreground "#111111"))))
 '(company-echo-common ((t (:foreground "#111111"))))
 '(company-tooltip-selection ((t (:background "#FFF1AA"))))
 '(parenface-paren-face ((t (:foreground "gray70"))))
 '(parenface-curly-face ((t (:foreground "gray70"))))
 '(parenface-bracket-face ((t (:foreground "gray70"))))
 '(parenthesis ((t (:foreground "gray70"))))
 '(sp-show-pair-match-face ((t (:foreground "black" :weight bold))))
 '(sp-show-pair-mismatch-face ((t (:background "red" :foreground "black" :weight bold))))
 '(show-paren-match ((t (:background "light green"))))
 '(show-paren-mismatch ((t (:background "red" :foreground "black" :weight bold))))
 '(js2-function-param ((t (:foreground "#111111"))))
 '(js2-external-variable ((t (:foreground "#111111"))))
 '(cperl-hash-face ((t (:foreground "#111111"))))
 '(cperl-array-face ((t (:foreground "#111111"))))
 '(cperl-nonoverridable-face ((t (:foreground "#111111"))))
 '(rpm-spec-tag-face ((t (:inherit default))))
 '(rpm-spec-package-face ((t (:inherit default))))
 '(rpm-spec-macro-face ((t (:inherit default))))
 '(rpm-spec-doc-face ((t (:inherit default))))
 '(rpm-spec-var-face ((t (:inherit default))))
 '(rpm-spec-ghost-face ((t (:inherit default))))
 '(rpm-spec-section-face ((t (:inherit default :weight bold))))
 '(nlinum-relative-current-face ((t (:inherit normal :weight bold))))
 '(linum ((t (:inherit normal :weight bold))))
 '(web-mode-current-element-highlight-face ((t (:inherit normal :weight bold :foreground "#111111"))))
 '(mmm-default-submode-face ((t (:inherit normal :background "#ffffef"))))
 '(idle-highlight ((t (:background "#FFF1AA"))))
 '(yas-field-highlight-face ((t (:background "#eeeee8" :foreground "#111111"))))
 '(eshell-prompt ((t (:foreground "#111111" :weight bold))))
 '(cider-result-overlay-face ((t (:weight bold))))
 '(evil-quickscope-first-face ((t (:foreground "#111111" :background "#eeeee8"))))
 '(evil-quickscope-second-face ((t (:foreground "#111111" :background "LightGreen"))))
 '(evil-snipe-first-match-face ((t (:foreground "#111111" :background "#eeeee8"))))
 '(evil-snipe-matches-face ((t (:foreground "#111111" :background "LightGreen"))))
 '(evil-ex-lazy-highlight ((t (:background "LightCyan"))))
 '(evil-ex-substitute-matches ((t (:background "LightCyan"))))
 '(evil-ex-substitute-replacement ((t (:background "#FFF1AA" :underline nil :foreground "#111111"))))
 '(default ((t (:background "#fffff8" :foreground "#111111")))))

(provide-theme 'mockingbird)
